FROM --platform=linux/amd64 python:3.11-slim-bookworm as builder

RUN --mount=type=cache,target=/var/cache/apt,sharing=private,id=apt_cache \
    --mount=type=cache,target=/var/lib/apt/lists,sharing=private,id=apt_lists \
    sed -i 's|http://deb.debian.org|https://mirrors.aliyun.com|g' /etc/apt/sources.list.d/debian.sources && \
    apt-get update -y && \
    apt-get install -y --no-install-recommends \
        libglib2.0-0 \
        ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN --mount=type=cache,target=/root/.cache/pip \
    python3 -m pip config set global.cache-dir /root/.cache/pip && \
    python3 -m pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple && \
    python3 -m pip install -U pip setuptools wheel

WORKDIR /app

COPY myocr /app/myocr
COPY models /app/models
COPY main.py pyproject.toml logging_config.yaml  /app/

RUN --mount=type=cache,target=/root/.cache/pip \
    python3 -m pip install --no-cache-dir . && \
    python3 -m pip install --no-cache-dir gunicorn && \
    python3 -m pip uninstall -y pip setuptools wheel && \
    find /usr/local/lib/python3.11 -type f -name '*.pyc' -delete && \
    find /usr/local/lib/python3.11 -type d -name '__pycache__' -exec rm -rf {} +

FROM --platform=linux/amd64 python:3.11-slim-bookworm

RUN --mount=type=cache,target=/var/cache/apt,sharing=private,id=apt_cache \
    --mount=type=cache,target=/var/lib/apt/lists,sharing=private,id=apt_lists \
    sed -i 's|http://deb.debian.org|https://mirrors.aliyun.com|g' /etc/apt/sources.list.d/debian.sources && \
    apt-get update -y && \
    apt-get install -y --no-install-recommends \
        libglib2.0-0 \
        ca-certificates \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder --chown=root:root /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages
COPY --from=builder --chown=root:root /usr/local/bin/gunicorn /usr/local/bin/
COPY --from=builder --chown=root:root /app /app

RUN find /app -type f -name '*.pyc' -delete && \
    find /app -type d -name '__pycache__' -exec rm -rf {} + && \
    rm -f /usr/local/bin/pip* /usr/local/bin/easy_install* || true

WORKDIR /app
EXPOSE 8000

CMD ["gunicorn", "-w", "4", "-k", "gthread", "-b", "0.0.0.0:8000", "main:app"]
