FROM --platform=linux/amd64 nvidia/cuda:12.4.1-cudnn-runtime-ubuntu22.04 as builder

RUN --mount=type=cache,target=/var/cache/apt,sharing=private,id=apt_cache \
    --mount=type=cache,target=/var/lib/apt/lists,sharing=private,id=apt_lists \
    sed -i 's|http://.*archive.ubuntu.com|https://mirrors.aliyun.com|g' /etc/apt/sources.list && \
    apt-get update -y && \
    apt-get install -y --no-install-recommends \
        software-properties-common \
        ca-certificates && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
        libgl1 \
        libgl1-mesa-glx \
        libglib2.0-0 \
        libsm6 \
        libxrender1 \
        libxext6 \
        tzdata \
        python3.11 \
        python3.11-dev \
        python3.11-distutils \
        curl && \
    update-ca-certificates && \
    ln -sf /usr/bin/python3.11 /usr/bin/python3 && \
    ln -sf /usr/bin/python3 /usr/bin/python

RUN --mount=type=cache,target=/root/.cache/pip \
    curl -sS https://bootstrap.pypa.io/get-pip.py | python3.11 && \
    python3.11 -m pip config set global.cache-dir /root/.cache/pip && \
    python3.11 -m pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple && \
    python3.11 -m pip install -U pip setuptools wheel

WORKDIR /app
COPY myocr /app/myocr
COPY models /app/models
COPY main.py pyproject.toml /app/

RUN --mount=type=cache,target=/root/.cache/pip \
    python3.11 -m pip install --ignore-installed . && \
    python3.11 -m pip install gunicorn


FROM --platform=linux/amd64 nvidia/cuda:12.4.1-cudnn-runtime-ubuntu22.04

RUN --mount=type=cache,target=/var/cache/apt,sharing=private,id=apt_cache \
    --mount=type=cache,target=/var/lib/apt/lists,sharing=private,id=apt_lists \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        python3.11 \
        ca-certificates \
        libgl1 \
        libgl1-mesa-glx \
        libglib2.0-0 \
        libsm6 \
        libxrender1 \
        libxext6 && \
    rm -rf /var/lib/apt/lists/* && \
    ln -sf /usr/bin/python3.11 /usr/bin/python3 && \
    ln -sf /usr/bin/python3 /usr/bin/python

COPY --from=builder --chown=root:root /usr/local/lib/python3.11/dist-packages /usr/local/lib/python3.11/dist-packages
COPY --from=builder --chown=root:root /usr/local/bin/gunicorn /usr/local/bin/
COPY --from=builder --chown=root:root /app /app

WORKDIR /app
EXPOSE 8000
CMD ["gunicorn", "-w", "4", "-k", "gthread", "-b", "0.0.0.0:8000", "main:app"]