name: structured_output_pipeline

chat_bot:
  model: qwen3:8b
  base_url: http://127.0.0.1:11434/v1
  api_key: 'key'
  sys_prompt: 'You are good at extracting information from the invoice, please extract corresponding information from the given texts recognized via OCR'