name: Release Docker Image

on:
  workflow_dispatch:

jobs:
  release-image:
    if: startsWith(github.ref, 'refs/tags/v')
    name: Release Docker Image
    runs-on: ubuntu-latest
    environment:
      name: release-new-version
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract version from tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/myocr:${{ env.RELEASE_VERSION }}
            ${{ secrets.DOCKER_USERNAME }}/myocr:latest
