name: Trigger Hugging Face Rebuild

on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    environment:
      name: release-new-version
    steps:
      - name: Set HF_USERNAME & HF_TOKEN variable
        env:
          HF_USERNAME : ${{ secrets.HF_USERNAME }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          echo "HF_USERNAME=${HF_USERNAME}" >> $GITHUB_ENV
          echo "HF_TOKEN=${HF_TOKEN}" >> $GITHUB_ENV

      - name: Configure git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      
      - name: Set up Git and push to Space
        run: |
          git clone https://huggingface.co/spaces/${HF_USERNAME}/myocr
          cd myocr
          git lfs install
          git lfs track "*.onnx"
          git add .
          git commit --allow-empty -m "empty commit to trigger rebuild"
          git push https://${HF_USERNAME}:${HF_TOKEN}@huggingface.co/spaces/${HF_USERNAME}/myocr main
